### PR TITLE
fix: error suppression in WithTimeout()

### LINKED ISSUE #31: [BUG] Silent failing on errors
When encountering an error (e.g. duplicate named tag in the same file, typo in the templating syntax in a markdown file or a cmd command), `hype` doesn't exit with an appropriate exit code and doesn't output an error message. This makes troubleshooting and with that an adoption of the tool difficult.

## Simple example to reproduce

test.md
```md
<code src="main.go" snippet="main"></code>
```

main.go
```go
package main

import (
	"fmt"
	"math/rand"
	"time"
)

// snippet: main
func main() {
	HelloWorld()
}

// snippet: main

// snippet: main
func HelloWorld() {
	fmt.Println("Hello, world!")
}

// snippet: main
```

Run `hype` to generate a final markdown:

```bash
bash-3.2$ hype export -f test.md -format markdown
bash-3.2$ echo $?
0
```

I would be happy to have a look at how to fix and open a pull request for that. Would that be okay with you?

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
Fixes #31 

Test with:

```go
go test -v -race -count=1 cli_errors_test.go
```

@corylanou @markbates let me know if there's a better way to test the built binary itself or if the test data should be structured differently. I'd be happy to make any further changes if need be.

### CODE REVIEW

File: cmd/hype/cli/cli.go [hunk 1]
```diff
@@ -197,24 +197,23 @@ func WithTimeout(ctx context.Context, timeout time.Duration, f func(context.Cont
...
-	cltx, cause := context.WithCancelCause(cltx)
+	defer cancel()
 
 	go func() {
-		defer cancel()
-		err := f(cltx)
-		if err != nil {
-			cause(err)
-		}
+		// TODO: check for context cancellation in f() to prevent leaking the goroutine
```
Comment (corylanou) [inline cmd/hype/cli/cli.go:205]: Is this still a TODO or was this fixed?

**Comment by corylanou** [comment]
This pr looks great.  Nice find!  I feel like the `TODO` comment has been addressed but I wasn't sure.  If it has if you can remove it (or I can) and then we can merge this.

Thanks for being part of this amazing project!

File: cmd/hype/cli/cli.go (hunk 1 above)
Comment (Kristina-Pianykh) [reply cmd/hype/cli/cli.go]: Theoretically, there is a scenario when the goroutine executing the callback in `WithTimeout()` is leaked. It would happen if the callback doesn't terminate before the timeout, and the context is cancelled. To prevent leaking the goroutine, the callback function should monitor the context and return when it's cancelled. I might be wrong, and I only skimmed through the code, but it seems like this is not the case. However, this is not critical since the error from canceling the context on timeout is lifted all the way up anyway, and the application exits with the respective exit code.

**Comment by Kristina-Pianykh** [comment]
> This pr looks great. Nice find! I feel like the `TODO` comment has been addressed but I wasn't sure. If it has if you can remove it (or I can) and then we can merge this.
> 
> Thanks for being part of this amazing project!

Thank you for the review, I'm happy to contribute! 
Removed the TODO comment. Feel free to merge whenever you're ready.

**Review by corylanou — APPROVED** [review]
Great job! Thank you!
